### ISSUE TITLE
bunx option

### ISSUE THREAD

**Issue by Bader-Idris** [ionic-team/vscode-ionic#135]
# announcement

After the latest bun update, I tried many `bunx`  commands with ionic and capacitor, and they all worked well, those commands are:

```sh
bunx cap run android
bunx vite build && bunx cap copy
bunx cap sync --inline
bunx vite build && bunx cap copy
bunx vite --no-open --host=0.0.0.0 --port=8100
bunx vite --open --host=0.0.0.0 --port=8100
bunx cap add ios
```

## wishing

please add the option of using `bun` with its `Bun Package Execute`, because it's faster than `npx`, and as you know, it has a promising future

**Comment by dtarnawsky** [comment]
Just to close out this issue. The extension is using bun commands if bun is used by the project. If there is a specific command that could be improved / changed for bun then please open another issue. The general comment about documentation I'll treat separately to this issue.
