### ISSUE TITLE
the extension is unable to find working directory

### ISSUE THREAD

**Issue by Bader-Idris** [ionic-team/vscode-ionic#136]
Since I have a full-stack project, I have included the front-end directory within the `client` subdirectory. This setup causes the `Ionic` extension to not recognize the workspace's working directory in Visual Studio Code. As a result, I am forced to open a separate Visual Studio Code window to access the extension's options.

> I tried settings > options

please use some regExp to make the extension understand subdirectories

**Comment by dtarnawsky** [comment]
Closing this issue as the original issue was addressed.
