### ISSUE TITLE
How to make the Nexus Browser auto-discover the local Dev Server application when running `ionic serve --external` via npm scripts

### ISSUE THREAD

**Issue by KoltonG** [ionic-team/vscode-ionic#145]
### Context

I've been really enjoying the **Ionic VSCode** extension and how the Nexus Browser on my phone just picks up the local Dev Server! As our project has gotten more and more complex, we've had to move away from using Run > Web (from the VSCode Extension) due to needing many environment variables and pre-build steps. 

### Question

The issue I am facing is that when I run `ionic serve --external` via npm scripts, the Nexus Browser doesn't see to auto-discover the local Dev Server like it does with Run > Web. I was wondering how does the Ionic VSCode extension does this, and if there is a way to enable this with the npm script way of running the application?

**Comment by dtarnawsky** [comment]
The Capacitor CLI has recently added a `--live-reload` option which the extension uses for live reload. The extension no longer uses the Ionic CLI and relies only on the Capacitor CLI and this means the command to run the dev server is now generated by the extensions and not the Ionic CLI. So, it should work, and is customizable by adding `ionic:build` to your `package.json` with whatever command want to use to build your app. If there are any other customizations needed then I can probably cater for them but you should be good to use either live reload or Nexus Browser for the feedback loop of your app.
