### ISSUE TITLE
Debugging web run failure after Cordova app migration

### ISSUE THREAD

**Issue by eskim023** [ionic-team/vscode-ionic#152]
New to Capacitor so apologies if I missed something obvious.  I successfully migrated my simple Cordova iOS app to Capacitor (nice work on that) and ran it on my native iOS devices.  And this is great! But I'm missing something when I use the VSCode extension to run on web.  This function in the Ionic VScode plugin results in this output:
```
[Ionic] Running on Web...
> npx undefined --no-open --host=0.0.0.0 --port=8100
npm error could not determine executable to run
```
...what executable should be running where we are seeing "undefined" and where is it set?  Chasing that dream of Live Reload...

Thanks so much.

**Comment by dtarnawsky** [comment]
Is this a project that you can share?

It sounds like the extension cannot identify how you would run your application - i.e. it's not Angular / React / Vue or has a serve or ionic:serve command in package.json.
