### ISSUE TITLE
"Error: pod: not found" on Linux

### ISSUE THREAD

**Issue by wsamoht** [ionic-team/vscode-ionic#157]
When the VSCode plugin is being used on a Linux machine, every time VSCode opens or reloads, the plugin throws the following error:

```
[error] /bin/sh: 1: pod: not found
```
It also happens when some Properties are changed, like the iOS Build Number. The change is successful but still throws the error.

It would be great if the OS was checked and if not a Mac, don't run the `pod` check.

This came up on the Ionic Forum [here](https://forum.ionicframework.com/t/error-bin-sh-1-pod-not-found/237948) :)

**Comment by dtarnawsky** [comment]
This should now be fixed in v1.89 released today.
