### ISSUE TITLE
do you plan to support electron integration in the vscode UI?

### ISSUE THREAD

**Issue by laurencefass** [ionic-team/vscode-ionic#160]
Im new to capacitor and the ionic plugin though i have managed to get an android image out and run it on my phone.

I want to output an electron image but their documentation is really sparse.

Do you plan to add electron integration  to the vscode extension ui?

Thanks

**Comment by dtarnawsky** [comment]
Electron is not an **officially** supported target platform, Capacitor **officially** supports iOS, Android and Web.

Electron exists on its own, independent of Capacitor, it doesn't support Capacitor plugins so there is little value proposition compared to a PWA / Web App which would provide the same functionality. So, my guess is that it is unlikely to supported in the future. It would be far more likely that someone would create an Electron VS Code extension as it is an independent product.

**Comment by laurencefass** [comment]
thanks for your feedback its very useful. the community electron package doesnt seem very well supported or up-to-date so Ill stick with PWA.
