### ISSUE TITLE
Bun monorepo support

### ISSUE THREAD

**Issue by Aksoom-Hussain** [ionic-team/vscode-ionic#184]
**Description**
specify the requirement for bun monorepo support in ionic vscode plugin

suggestion to add optimum instruction in documentation

[feature request also mentioned here](https://github.com/ionic-team/capacitor/issues/7636)

**Comment by dtarnawsky** [comment]
Hey Axum,

Do you have a sample project that use bun in a monorepo setting that I can use for testing?

**Comment by oalexdoda** [comment]
@dtarnawsky I believe this spins up a quick Bun monorepo:

https://bun.sh/guides/ecosystem/nextjs

I have the same feature request as the OP. Bun.sh is incredibly powerful and fast compared to other package managers. Gained a lot of popularity recently so I'd love to see support for it.

**Comment by dtarnawsky** [comment]
Hi @oalexdoda, I tried out the bun setup guide for nextJS [here](https://bun.sh/guides/ecosystem/nextjs) which will work fine with the extension. 

For NextJS you just need to edit `next.config.mjs` and add `output: export` to the settings as documented [here](https://nextjs.org/docs/pages/building-your-application/deploying/static-exports). This puts your static assets in the `out` folder and so in `capacitor.config.ts` you just need to set the `webDir: 'out'`.

For bun monorepos, they do look and act a lot like npm workspaces which the VS Code extension supports. In doing a simple test for a mono-repo it seems to work but it is really dependence on how the mono repo folder structure looks.

So, @Aksoom-Hussain , I need a sample repo to work with to find any bugs that may be occurring.

**Comment by dtarnawsky** [comment]
Closing out this ticket as it requires a bun mono repo sample that has an issue. This can be reopened when a reproduction is given.
