### ISSUE TITLE
 v.1.93.4: The debugging option has stopped working, and now it is also required that libraries using confidential information must run under HTTPS

### ISSUE THREAD

**Issue by factorx22** [ionic-team/vscode-ionic#192]
When observing the command executed for debugging, it shows that it runs in Production mode, whereas it previously ran in Developer mode (the breakpoints don't work).  

Now, when using confidential functions, such as requesting location or microphone permissions in the browser, they have stopped working because these require HTTPS. In the previous debugging version, this wasn't necessary.

**Comment by dtarnawsky** [comment]
Hi,

This problem should now be fixed in v1.94 released today.

**Comment by factorx22** [comment]
Great!

**Comment by szyszak** [comment]
I'm encountering the same issue with v1.94.1: the production bundle is being served, and I can't set any breakpoints.

**Comment by dtarnawsky** [comment]
Hi @szyszak, thanks for the report: I just fixed this for v1.94.2 in this [PR](https://github.com/ionic-team/vscode-ionic/pull/201). If you have any other issues please open a new issue.
