### ISSUE TITLE
Run build with error since version 1.96.0

### ISSUE THREAD

**Issue by Valentoche** [ionic-team/vscode-ionic#211]
On an Angular project I've just initialized, when i use the build button
![image](https://github.com/user-attachments/assets/b9fa6481-78cb-4477-95b8-dc20a84449e5)

I have this error : 
![image](https://github.com/user-attachments/assets/d518a7d8-28f4-449b-b887-10842cef0a4d)

Thanks for your support.

**Comment by dtarnawsky** [comment]
v1.96.1 is out now and should fix this issue. Please let me know.

**Comment by Valentoche** [comment]
It works now, thank you.
