### ISSUE TITLE
Automatic Import isn't working for standalone components

### ISSUE THREAD

**Issue by rickdmer** [ionic-team/vscode-ionic#214]
Ionic/angular version 8.3.3
VS Code version 1.94.2
Ionic Extension version 1.97.2

To reproduce:
1. Create an Ionic starter application using ionic start
2. Select Angular and use standalone components.
3. Open the project folder in VS Code
4. In app/home/home.page.html, add <ion-grid></ion-grid> in the existing ion-container block.

Expected:
- The ion-grid imports are added to home.page.ts

Actual:
- Nothing is added to the home.page.ts

**Comment by rickdmer** [comment]
Troubleshooting done:
- Reinstall VS code
- Reinstall extension
- Tried an old version of Ionic Extension (1.68)
- Disabled all other extensions

**Comment by rickdmer** [comment]
Reading through another open issue, I saw someone who had this working had a plugin called Angular Language Service installed. I installed that plugin and this started working.

**Comment by jayavarmar** [comment]
But For me it is not working, 

For me angular language service is throwing this following warning and auto imports is also not working for ionic components

WARNING:
A project in the workspace is using a newer version of Angular than the language service extension. This may cause the extension to show incorrect diagnostics.
