### ISSUE TITLE
official plugins cause app building to crash

### ISSUE THREAD

**Issue by Bader-Idris** [ionic-team/vscode-ionic#215]
these two packages cause the Android studio building process to crash

```json
"@capacitor/barcode-scanner": "^1.0.1",
"@capacitor/inappbrowser": "^1.0.2",
```

the crash message outputs a conflict with Kotlin versions

```sh
Unknown Kotlin JVM target: 21
```

The Android Studio version I use is the latest

**Comment by dtarnawsky** [comment]
This issue is unrelated to the VS Code extension and would be best sent over to: https://github.com/ionic-team/capacitor-plugins (note: you probably need to set the correct JDK version in Android studio).

**Comment by Bader-Idris** [comment]
I have sent it to them, and the JDK version is 22 or 23, so it's way higher than the required version
