### ISSUE TITLE
Unbound breakpoint when using Ionic extension in VSCode

### ISSUE THREAD

**Issue by bengrah-miller** [ionic-team/vscode-ionic#216]
Hi guys,

I'm using the Ionic extension in VSCode, specifically using the 'Debug' option to connect to my app on my device. It looks like I'm able to connect to the device, but when I try to set a breakpoint, I get the following:

![image](https://github.com/user-attachments/assets/dc9d6440-7ff2-4a0e-b5f1-88275ef9da7a)

It does mention about 'troubleshooting your launch configuration' but it looks like there isn't anything like the previous launch.json file that there was with Cordova.

Any ideas?

Thanks,
bengrah.

**Comment by dtarnawsky** [comment]
Are you trying to debug a production build? Source maps need to be enabled which will typically be configured for a development build. Are you using React, Vue, JS, Angular? Are you using the Ionic framework? Can you provide a reproduction project?

**Comment by bengrah-miller** [comment]
Hi @dtarnawsky ,

It's an Ionic Capacitor project. Where do you configure the source maps setting?

Ben.

**Comment by dtarnawsky** [comment]
That depends on the questions I asked. For example, in Angular, the `sourceMap` property is found in `angular.json`.

**Comment by bengrah-miller** [comment]
Hi @dtarnawsky I do have `sourceMap` configured under the `development` configuration, and I've just added it to `production` configuration:

![image](https://github.com/user-attachments/assets/af4a3ce8-003a-4e84-91e5-70839bf2b086)

I'm able to get breakpoints now - thanks for your help.

bengrah.
