### ISSUE TITLE
'Prepare Release' command is impractical to use with long keystore passwords

### ISSUE THREAD

**Issue by davidgeary** [ionic-team/vscode-ionic#219]
I've tried to use the 'Prepare Release' command but there doesn't seem to be a way to complete the process if both your keystore and key are password-protected with passwords that are long (i.e. secure) enough that you need to use copy/paste.

The issue is that the window prompting for the passwords is dismissed if you click away from it.  This is avoidable when it's prompting for the keystore password as you can copy the password to the clipboard first, then start the command and paste the password when requested.  But if your key also has a long password, as soon as you navigate to, say, your password manager to copy it, the window disappears, cancelling the command.

![vscode-cmd-window](https://github.com/user-attachments/assets/8cca0bbb-8272-44bd-b236-a90adb7f777f)

Obviously, you can get around this by typing the command, rather than copy-n-pasting, but this would discourage the use of long, secure passwords.

Is it possible to force the window to stay open or is this a restriction of the VS Code UI/extension API? (Or am I missing some other trick?)

**Comment by dtarnawsky** [comment]
Hey @davidgeary , I've found a potential fix for this that prevents the dialog from closing when it loses focus. This is implemented in v1.99 which will come out soon (it's in the same batch as the changes for the migration to Angular 19 which are waiting on a release of [angular-eslint](https://github.com/angular-eslint/angular-eslint/pull/2109)).
